dist: xenial
language: python
python:
- "3.7-dev"
# setup environment
env:
- DJANGO_VERSION=2.2
# install dependencies
install:
- pip install -r requirements.txt
- pip install codecov

# run test scripts
script:
- coverage run --source='.' manage.py test

# Push the results back to codecov
after_success:
- codecov
