language: python
python:
- "3.7-dev"
# setup environment
env:
- DJANGO_VERSION=2.2
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py test
