# Generated by Django 2.1.7 on 2019-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('started', models.BooleanField()),
                ('run_type', models.CharField(max_length=20)),
                ('hashtag', models.CharField(max_length=150)),
                ('other_profile', models.CharField(max_length=150)),
            ],
        ),
    ]
