# Generated by Django 2.1.7 on 2019-03-21 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190321_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 18, 33, 257307, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 18, 33, 257307, tzinfo=utc)),
        ),
    ]
